task 3
Artyom43/Android-Mipt-Kotlin-2024-Mullin pull request #3
Opened 2024-02-17 19:18 UTC by Artyom43

2024-03-02 19:08 UTC, Ksalim01 requested changes

2024-03-02 19:08 UTC, Ksalim01 commented on src/main/kotlin/3.kt
> +        }
Добавь вместо этого метод insert и убери параметры конструктора. Старайся писать более общее решение)

2024-03-11 17:03 UTC, Artyom43 commented on src/main/kotlin/3.kt
> +        }
Поправил

2024-03-15 09:09 UTC, Ksalim01 commented on src/main/kotlin/3.kt
> +        } else {
```
if (root == null) {
    root = Node(value)
    return    
}
// дальше все под скоупом else
```

2024-03-15 09:10 UTC, merged