text task
Artyom43/Android-Mipt-Kotlin-2024-Mullin pull request #6
Opened 2024-02-17 19:21 UTC by Artyom43

2024-03-10 14:30 UTC, Ksalim01 requested changes
Решение неоптимально, поэтому чтобы получить полный балл, нужно сделать его таким. Смотри третий пункт критериев оценивания задачи

2024-03-10 14:30 UTC, Ksalim01 commented on src/main/kotlin/zoo/animal/SoundMaker.kt
> +interface SoundMaker {
Ну можно было для приличия добавить метод какой-нибудь

2024-03-10 14:30 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun removeAnimalById(id: Int) = animals.removeIf { it.id == id }
А из supervisorToAnimal удалять не нужно?

2024-03-10 14:30 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun findAnimalBySupervisorsName(name: String) = supervisorToAnimal.filterKeys { it.name == name }.values.toList()
Не самые оптимальные с точки зрения времени решения

2024-03-10 14:30 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun findEnoughHighAnimal (height: Int) = animals.filter { it.height > height }
animals это дерево, и тут стоит применить это свойство для получения животных выше нужного, иначе смысл этого метода и самого хранения животных в дереве теряется

2024-03-13 17:39 UTC, Artyom43 commented on src/main/kotlin/zoo/animal/SoundMaker.kt
> +interface SoundMaker {
Добавил)

2024-03-13 17:40 UTC, Artyom43 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun removeAnimalById(id: Int) = animals.removeIf { it.id == id }
Поправил

2024-03-13 17:40 UTC, Artyom43 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun findAnimalBySupervisorsName(name: String) = supervisorToAnimal.filterKeys { it.name == name }.values.toList()
Поправил

2024-03-13 17:40 UTC, Artyom43 commented on src/main/kotlin/zoo/Zoo.kt
> +    fun findEnoughHighAnimal (height: Int) = animals.filter { it.height > height }
Поправил

2024-03-15 09:06 UTC, Ksalim01 requested changes
Везде должна быть наилучшая асимптотика времени. Также убери проброс исключений

2024-03-15 09:06 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +        animals.find { it.id == id } ?: throw IllegalArgumentException("No animal with id: $id")
Снова не самое быстрое. Заведи еще одну хэшмапу для этого

2024-03-15 09:06 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +        throw IllegalArgumentException("No supervisor with id: $id")
почему бы не вернуть пустой массив? Лучше избегать исключений

2024-03-15 09:06 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +        }
снова не быстрое

2024-03-15 09:06 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +        }
И тут не самое быстрое

2024-03-15 09:06 UTC, Ksalim01 commented on src/main/kotlin/zoo/Zoo.kt
> +        result = result or (supervisorToAnimal[findSupervisorByAnimalId(id)]?.removeIf { it.id == id } == true)
1. Тут тоже не быстро
2. Лучше использовать свзяку if + return, т.к. так плохо читается

2024-03-31 07:36 UTC, merged